name: Deno
on:
  push:
    branches:
      - master
      - dev
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Compile for Deno
        run: npm run compile:deno

      - name: Copy extra files
        run: cp {LICENSE,README.md} dist/deno

      - name: Push to deno branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deno
          FOLDER: dist/deno
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
